=== StellaSmith/little_game/res/schemas/ModelSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "required": [
        "vertices",
        "faces",
        "license",
        "author"
    ],
    "additionalProperties": false,
    "properties": {
        "author": {
            "type": "object",
            "additionalProperties": false,
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "contact": {
                    "union": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "minItems": 2,
                            "items": {
                                "type": "string"
                            }
                        }
                    ]
                },
                "url": {
                    "union": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "minItems": 2,
                            "items": {
                                "type": "string"
                            }
                        }
                    ]
                }
            }
        },
        "license": {
            "type": "string"
        },
        "url": {
            "type": "string"
        },
        "comment": {
            "union": [
                {
                    "type": "string"
                },
                {
                    "type": "array",
                    "minItems": 2,
                    "items": {
                        "type": "string"
                    }
                }
            ]
        },
        "vertices": {
            "type": "array",
            "minItems": 3,
            "items": {
                "type": "object",
                "required": [
                    "position",
                    "uv"
                ],
                "additionalProperties": false,
                "properties": {
                    "position": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        },
                        "minItems": 2,
                        "maxItems": 3
                    },
                    "uv": {
                        "type": "array",
                        "items": {
                            "type": "number",
                            "minItems": 2,
                            "maxItems": 2
                        }
                    }
                }
            }
        },
        "faces": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": [
                    "indices",
                    "sides",
                    "texture"
                ],
                "additionalProperties": false,
                "properties": {
                    "indices": {
                        "type": "array",
                        "minItems": 3,
                        "items": {
                            "type": "integer",
                            "minimum": 0,
                            "maximum": 4294967295
                        }
                    },
                    "sides": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "string",
                            "enum": [
                                "top",
                                "north",
                                "west",
                                "east",
                                "south",
                                "bottom"
                            ]
                        }
                    },
                    "texture": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 4294967295
                    },
                    "solid": {
                        "type": "boolean",
                        "default": true
                    }
                }
            }
        }
    }
}

=== StellaSmith/little_game/assets/models/blocks/CommonBlock.json
{
    "author": {
        "name": "Stella Smith",
        "url": "https://github.com/StellaSmith/"
    },
    "license": "GPL-2.0",
    "url": "https://github.com/StellaSmith/little_game/",
    "comment": "A Cube",
    "vertices": [
        {
            "position": [
                -0.5,
                0.5,
                -0.5
            ],
            "uv": [
                0.0,
                0.0
            ]
        },
        {
            "position": [
                -0.5,
                0.5,
                0.5
            ],
            "uv": [
                0.0,
                1.0
            ]
        },
        {
            "position": [
                0.5,
                0.5,
                0.5
            ],
            "uv": [
                1.0,
                1.0
            ]
        },
        {
            "position": [
                0.5,
                0.5,
                -0.5
            ],
            "uv": [
                1.0,
                0.0
            ]
        },
        {
            "position": [
                0.5,
                0.5,
                -0.5
            ],
            "uv": [
                0.0,
                0.0
            ]
        },
        {
            "position": [
                0.5,
                -0.5,
                -0.5
            ],
            "uv": [
                0.0,
                1.0
            ]
        },
        {
            "position": [
                -0.5,
                -0.5,
                -0.5
            ],
            "uv": [
                1.0,
                1.0
            ]
        },
        {
            "position": [
                -0.5,
                0.5,
                -0.5
            ],
            "uv": [
                1.0,
                0.0
            ]
        },
        {
            "position": [
                -0.5,
                0.5,
                -0.5
            ],
            "uv": [
                0.0,
                0.0
            ]
        },
        {
            "position": [
                -0.5,
                -0.5,
                -0.5
            ],
            "uv": [
                0.0,
                1.0
            ]
        },
        {
            "position": [
                -0.5,
                -0.5,
                0.5
            ],
            "uv": [
                1.0,
                1.0
            ]
        },
        {
            "position": [
                -0.5,
                0.5,
                0.5
            ],
            "uv": [
                1.0,
                0.0
            ]
        },
        {
            "position": [
                0.5,
                0.5,
                0.5
            ],
            "uv": [
                0.0,
                0.0
            ]
        },
        {
            "position": [
                0.5,
                -0.5,
                0.5
            ],
            "uv": [
                0.0,
                1.0
            ]
        },
        {
            "position": [
                -0.5,
                -0.5,
                0.5
            ],
            "uv": [
                1.0,
                1.0
            ]
        },
        {
            "position": [
                -0.5,
                0.5,
                0.5
            ],
            "uv": [
                1.0,
                0.0
            ]
        },
        {
            "position": [
                0.5,
                0.5,
                -0.5
            ],
            "uv": [
                0.0,
                0.0
            ]
        },
        {
            "position": [
                0.5,
                -0.5,
                -0.5
            ],
            "uv": [
                0.0,
                1.0
            ]
        },
        {
            "position": [
                0.5,
                -0.5,
                0.5
            ],
            "uv": [
                1.0,
                1.0
            ]
        },
        {
            "position": [
                0.5,
                0.5,
                0.5
            ],
            "uv": [
                1.0,
                0.0
            ]
        },
        {
            "position": [
                -0.5,
                -0.5,
                -0.5
            ],
            "uv": [
                0.0,
                0.0
            ]
        },
        {
            "position": [
                -0.5,
                -0.5,
                0.5
            ],
            "uv": [
                0.0,
                1.0
            ]
        },
        {
            "position": [
                0.5,
                -0.5,
                0.5
            ],
            "uv": [
                1.0,
                1.0
            ]
        },
        {
            "position": [
                0.5,
                -0.5,
                -0.5
            ],
            "uv": [
                1.0,
                0.0
            ]
        }
    ],
    "faces": [
        {
            "indices": [
                0,
                1,
                2,
                3
            ],
            "sides": [
                "top"
            ],
            "texture": 0,
            "solid": true
        },
        {
            "indices": [
                4,
                5,
                6,
                7
            ],
            "sides": [
                "north"
            ],
            "texture": 0,
            "solid": true
        },
        {
            "indices": [
                8,
                9,
                10,
                11
            ],
            "sides": [
                "west"
            ],
            "texture": 0,
            "solid": true
        },
        {
            "indices": [
                12,
                13,
                14,
                15
            ],
            "sides": [
                "south"
            ],
            "texture": 0,
            "solid": true
        },
        {
            "indices": [
                16,
                17,
                18,
                19
            ],
            "sides": [
                "east"
            ],
            "texture": 0,
            "solid": true
        },
        {
            "indices": [
                20,
                21,
                22,
                23
            ],
            "sides": [
                "bottom"
            ],
            "texture": 0,
            "solid": true
        }
    ]
}
